hack for Make_Tree error
/usr/lib/atlas-base/ -D_GNU_SOURCE -DHTABLE='"/usr/local/share/igphyml/src/motifs/HTABLE_"' -I/usr/include/atlas/ -MT utilities.o -MD -MP -MF .deps/utilities.Tpo -c -o utilities.o utilities.c
utilities.c: In function ‘Make_Tree_From_Scratch’:
utilities.c:1006:10: error: too many arguments to function ‘Make_Tree’; expected 0, have 1
1006 | tree = Make_Tree(n_otu);
| ^~~~~~~~~ ~~~~~
In file included from utilities.c:26:
utilities.h:1561:9: note: declared here
1561 | t_tree *Make_Tree();
| ^~~~~~~~~
utilities.c: At top level:
utilities.c:1019:9: error: conflicting types for ‘Make_Tree’; have ‘t_tree *(int)’ {aka ‘struct __Arbre *(int)’}
1019 | t_tree *Make_Tree(int n_otu){
| ^~~~~~~~~
utilities.h:1561:9: note: previous declaration of ‘Make_Tree’ with type ‘t_tree *(void)’ {aka ‘struct __Arbre *(void)’}
1561 | t_tree *Make_Tree();
| ^~~~~~~~~
make[2]: *** [Makefile:699: utilities.o] Error 1
make[2]: Leaving directory '/usr/local/share/igphyml/src'
make[1]: *** [Makefile:371: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/share/igphyml'
make: *** [Makefile:312: all] Error 2

There is a mismatch between the declaration and definition of the Make_Tree function in the IgPhyML source code:

- In utilities.h, it is declared as t_tree *Make_Tree(); (no arguments).
- In utilities.c, it is defined as t_tree *Make_Tree(int n_otu) (takes an int argument).
- In utilities.c, it is called as Make_Tree(n_otu);.